@startuml

object "Triangulo1:Poligono" as T1
object "Triangulo2:Poligono" as T2
object ":Punto" as P1{
    cord_x = 0
    cord_y = 0
}
object ":Punto" as P2{
    cord_x = 10
    cord_y = 0
}
object ":Punto" as P3{
    cord_x = 10
    cord_y = 10
}
object ":Punto" as P4{
    cord_x = 20
    cord_y = 0 
}

T1 -left- P1
T1 -right- P2
T1 -down- P3
T2 -left- P2
T2 -down- P3
T2 -right- P4

@enduml