@startuml sequenceDiagram

participant ": Cliente" as cliente
participant "miLista : Lista" as miLista
participant "item : Item" as Item

activate cliente
cliente -> miLista: 1:getItem()

activate miLista
miLista --> cliente: 1.1:item
deactivate miLista

cliente -> Item: 2:hacerAlgo()

activate Item

footer (miLista.getItem()).hacerAlgo()

@enduml