@startuml getNombreEstudiante

participant ": Cliente" as cliente
participant "miColeccion : Coleccion" as miColeccion
participant "i : Estudiante" as Estudiante

activate cliente
cliente -> miColeccion: 1:getEstudiante(i)

activate miColeccion
miColeccion --> cliente: 1.1:i
deactivate miColeccion

cliente -> Estudiante: 2:getNombre()
activate Estudiante

Estudiante --> cliente: 2.1:Nombre

footer miColeccion.getEstudiante(i).getNombre()

@enduml