@startuml lista

participant ": Cliente" as cliente
participant "textField : TextField" as textField
participant "lista : Lista" as lista

activate cliente
cliente -> textField: 1:getText()

activate textField
textField --> cliente: 1.1:string
deactivate textField

cliente -> lista: 2:add(string)
activate lista

footer lista.add(textField.getText())

@enduml