@startuml
participant PruebaE1 order 2
participant ClienteE1 order 1


create PruebaE1
ClienteE1 -> PruebaE1:new
activate PruebaE1


note left of ClienteE1
    public class PruebaE1{
    public void f(){ g(); }
    public void g(){ h(); }
    public void h(){ System.out.println("Algo"); }
    }
    public class ClienteE1 {
    public static void main(String[] args) {
    Prueba p = new PruebaE1();
    p.f();
    }
    }
end note

@enduml