@startuml pruebaCliente
participant "p : PruebaE1" as PruebaE1 order 2
participant ": ClienteE1" as ClienteE1 order 1

activate ClienteE1
create PruebaE1
ClienteE1 -> PruebaE1: 1:create
activate PruebaE1

ClienteE1 -> PruebaE1: 2:f()
deactivate ClienteE1
PruebaE1 -> PruebaE1: 2.1:g()
PruebaE1 -> PruebaE1: 2.2:h()

@enduml